# -*- coding: utf-8 -*-
"""helper_functions_Music_generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oSJHuR0YOwl_Vm9bRCuM7vhjTwfepops
"""

import os
import subprocess

def download_youtube_audio_from_list(urls, output_folder='audio_files', audio_format='mp3'):
    """
    Download audio from a list of YouTube video URLs and save it to a specified folder.

    Parameters:
    - urls (list): A list of YouTube video URLs.
    - output_folder (str): The folder where the audio files will be saved.
    - audio_format (str): The audio format for the output files (default is 'mp3').

    Returns:
    - list: A list of paths to the downloaded audio files.
    """
    # Create the output folder if it doesn't exist
    os.makedirs(output_folder, exist_ok=True)

    downloaded_files = []

    for url in urls:
        # Check if the URL is a YouTube link
        if "youtube.com/watch?v=" in url or "youtu.be/" in url:
            # Construct the command to get the video title
            command = f'yt-dlp --get-title "{url}"'

            # Execute the command to get the title
            try:
                title = subprocess.check_output(command, shell=True, text=True).strip()
            except subprocess.CalledProcessError as e:
                print(f"Error getting video title for {url}: {e}")
                continue

            # Construct the command to download the audio
            command = f'yt-dlp -x --audio-format {audio_format} -o "{output_folder}/{title}.%(ext)s" "{url}"'

            # Execute the command to download audio
            try:
                subprocess.run(command, shell=True, check=True)
                print(f"Downloaded audio: {title}.{audio_format} to {output_folder}.")

                # Append the path to the downloaded file
                downloaded_file = os.path.join(output_folder, f"{title}.{audio_format}")
                downloaded_files.append(downloaded_file)
            except subprocess.CalledProcessError as e:
                print(f"Error occurred during download for {url}: {e}")
                continue
        else:
            print(f"Skipping non-YouTube URL: {url}")

    return downloaded_files

